name: Env Variable Workflow

on:
  workflow_dispatch:

env:
  ENV: staging   # Available to all jobs

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print ENV variable
        run: echo "Workflow environment is $ENV"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Use ENV in second job
        run: echo "Deploying to $ENV environment"
